-- MySQL Script generated by MySQL Workbench
-- Thu Dec 26 13:46:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mydb2
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Dept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dept` (
  `dno` INT NOT NULL,
  `dname` VARCHAR(45) NOT NULL,
  `dcall` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `ssn` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `gra/se` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `Dept_dno` INT NOT NULL,
  PRIMARY KEY (`ssn`),
  INDEX `fk_Student_Dept1_idx` (`Dept_dno` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Dept1`
    FOREIGN KEY (`Dept_dno`)
    REFERENCES `mydb`.`Dept` (`dno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `ssn` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `Dept_dno` INT NOT NULL,
  PRIMARY KEY (`ssn`),
  INDEX `fk_Professor_Dept1_idx` (`Dept_dno` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Dept1`
    FOREIGN KEY (`Dept_dno`)
    REFERENCES `mydb`.`Dept` (`dno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lecture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lecture` (
  `lno` INT NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  `credit` VARCHAR(45) NOT NULL,
  `ltime` VARCHAR(45) NOT NULL,
  `room` VARCHAR(45) NOT NULL,
  `Professor_ssn` INT NOT NULL,
  PRIMARY KEY (`lno`),
  INDEX `fk_Lecture_Professor_idx` (`Professor_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Lecture_Professor`
    FOREIGN KEY (`Professor_ssn`)
    REFERENCES `mydb`.`Professor` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Couuse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Couuse` (
  `cno` INT NOT NULL,
  `Student_ssn` INT NOT NULL,
  `Lecture_lno` INT NOT NULL,
  PRIMARY KEY (`cno`, `Student_ssn`, `Lecture_lno`),
  INDEX `fk_Couuse_Student1_idx` (`Student_ssn` ASC) VISIBLE,
  INDEX `fk_Couuse_Lecture1_idx` (`Lecture_lno` ASC) VISIBLE,
  CONSTRAINT `fk_Couuse_Student1`
    FOREIGN KEY (`Student_ssn`)
    REFERENCES `mydb`.`Student` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Couuse_Lecture1`
    FOREIGN KEY (`Lecture_lno`)
    REFERENCES `mydb`.`Lecture` (`lno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Charge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Charge` (
  `chr_no` INT NOT NULL,
  `Student_ssn` INT NOT NULL,
  `Professor_ssn` INT NOT NULL,
  PRIMARY KEY (`chr_no`, `Student_ssn`, `Professor_ssn`),
  INDEX `fk_Charge_Student1_idx` (`Student_ssn` ASC) VISIBLE,
  INDEX `fk_Charge_Professor1_idx` (`Professor_ssn` ASC) VISIBLE,
  CONSTRAINT `fk_Charge_Student1`
    FOREIGN KEY (`Student_ssn`)
    REFERENCES `mydb`.`Student` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Charge_Professor1`
    FOREIGN KEY (`Professor_ssn`)
    REFERENCES `mydb`.`Professor` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
